### ISSUE TITLE
Understand the code base

### ISSUE THREAD

**Issue by aranganath** [aranganath/new-cubic-video-interpolation#8]
Visit [this](https://github.com/xuxy09/QVI) to understand the code which is for [this](https://github.com/xuxy09/QVI).

Here is what you are going to be doing/on the lookout for:
1. Run the code to check whether it works. You will be using the credentials I will be sending you over slack.
2. Make sure you are able to see the results. There are tensor board instances running once you run the code. Make sure you are able to track the training accuracy. 
3. Keep on the lookout for the 'PWC-net' model. This needs to be replaced with SpyNet (you don't have to do this now, but we might have to do this once we get to this.).

**Comment by rssmith614** [comment]
![Screenshot 2023-05-28 at 10 25 22 AM](https://github.com/aranganath/new-cubic-video-interpolation/assets/16826903/fbd63b4d-ba49-4e61-88e7-5b1f83657f90)
